name: docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Install sqlite
        run: sudo apt-get install sqlite libyaml-dev

      - name: Set the VIRTUAL_ENV variable for uv to work
        run: |
          echo "VIRTUAL_ENV=${Python_ROOT_DIR}" >> $GITHUB_ENV

      - name: Update pip/wheel infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install wheel

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt

      - name: Build and install
        run: uv pip install --no-deps -v -e .

      - name: Install documenteer
        run: uv pip install 'documenteer[pipelines]==0.8.2'

      - name: Build documentation
        env:
          DAF_BUTLER_MIGRATE_DIR: .
          DAF_BUTLER_MIGRATE_MIGRATIONS: ./migrations
        working-directory: ./doc
        run: package-docs build -n -W

      - name: Upload to LSST the Docs
        uses: lsst-sqre/ltd-upload@v1
        with:
          project: 'daf-butler-migrate'
          dir: 'doc/_build/html'
          username: ${{ secrets.LTD_USERNAME }}
          password: ${{ secrets.LTD_PASSWORD }}
